name: ExtDN PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: extdn/github-actions-m2/magento-phpstan/8.3@master
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
          composer_version: 2
          phpstan_level: 1
          magento_pre_install_script: .github/workflows/extdn-phpstan-tests-pre-install.sh
